### ISSUE TITLE
Latest update gives error

### ISSUE THREAD

**Issue by JohnnyS** [Xxpromw3mtxX/cosmo_hud#14]
![image](https://user-images.githubusercontent.com/62607662/154376431-083ef41f-63b8-4f28-bc40-ffbf0447dcac.png)

![image](https://user-images.githubusercontent.com/62607662/154376439-951f4561-543c-4044-b45a-fcbf1ce82957.png)

This is with the latest update you put out and on a 1440p monitor

**Comment by Xxpromw3mtxX** [comment]
Okay so the problem there is that it's not responsive, so it doesn't change position based on the resolution. This might be an improvement.
Re-download the [lastest release](https://github.com/Xxpromw3mtxX/cosmo_hud/releases/tag/1.2.0) because we've updated it.
If still getting the error, there's something misconfigured with the stress system in your server.
Lemme know! Here to help :D
